[project]
name = "hexlet-code"
version = "0.1.0"
dependencies = [
    "django>=6.0.1",
    "python-dotenv>=1.2.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["task_manager"]
